import type { CodeReviewResponse } from "@/types/learning";
import styles from "./AIReviewPanel.module.css";

type Props = {
  review: CodeReviewResponse | null;
  state?: "idle" | "loading" | "unavailable";
};

export function AIReviewPanel({ review, state = "idle" }: Props) {
  if (!review && state === "idle") return null;

  if (!review) return (
    <section className={`${styles.panel} ${state === "unavailable" ? styles.unavailable : ""}`} aria-live="polite">
      <div className={styles.heading}>
        <span>{state === "loading" ? "✦ CONTACTING GEMINI AI" : "GEMINI AI REVIEW UNAVAILABLE"}</span>
        <b>{state === "loading" ? "ANALYZING" : "OFFLINE"}</b>
      </div>
      <p>{state === "loading"
        ? "Gemini is reviewing the submitted code using the prompt and verified test evidence."
        : "Gemini could not be reached for this attempt. Your test results and deterministic diagnosis are still available, but no AI-generated review was produced."}</p>
    </section>
  );

  const isGemini = review.source === "gemini";
  return (
    <section className={`${styles.panel} ${isGemini ? styles.ai : styles.unavailable}`} aria-label={isGemini ? "Gemini AI code review" : "Test-based fallback review"}>
      <div className={styles.heading}>
        <span>{isGemini ? "✦ GEMINI AI CODE REVIEW" : "GEMINI AI REVIEW UNAVAILABLE"}</span>
        <b>{isGemini ? review.model : "TEST-BASED FALLBACK"}</b>
      </div>
      <p className={styles.disclosure}>{isGemini
        ? "This explanation was generated by Gemini from your code and verified test evidence. Test results remain the source of truth."
        : `Gemini did not produce this review. ${review.availabilityMessage ?? "The provider was unavailable for this request."} The guidance below was generated deterministically from verified tests and diagnosis evidence.`}</p>
      <h3>{review.summary}</h3>
      {review.strengths.length ? <div className={styles.section}><strong>What worked</strong><ul>{review.strengths.map(item => <li key={item}>{item}</li>)}</ul></div> : null}
      {review.issues.length ? <div className={styles.section}><strong>What to inspect</strong><ul>{review.issues.map((item, index) => <li key={`${item.title}-${index}`}><b>{item.line ? `Line ${item.line}: ` : ""}{item.title}</b><span>{item.explanation}</span></li>)}</ul></div> : null}
      {review.nextSteps.length ? <div className={styles.section}><strong>Recommended next step</strong><ol>{review.nextSteps.map(item => <li key={item}>{item}</li>)}</ol></div> : null}
    </section>
  );
}
