export interface TopicLesson {
  title: string;
  subtitle: string;
  objective: string;
  exerciseId?: string;
  introduction: { heading: string; body: string[]; code: string; walkthrough: string[] };
  sections: { heading: string; body: string; code?: string; takeaway?: string }[];
  checkpoint: string;
  practicePrompt: string;
  workedExamples: { title: string; code: string; explanation: string; output: string }[];
  commonMistakes: { mistake: string; correction: string }[];
  recap: string[];
  sources: { label: string; url: string }[];
}

export const topicLessons: Record<string, TopicLesson> = {
  variables: {
    title: "Variables & values", subtitle: "Give information a name so your program can remember it.", objective: "Create a variable, read its value, and update it when your program needs to remember something new.",
    exerciseId: "starting-value-01",
    introduction: { heading: "How variables work", body: ["A variable is a name your program uses to refer to a value. Think of it as a label attached to information: instead of remembering that Maya's score is 12 everywhere in the program, you can store it once as `score` and use that name wherever you need it.", "When Python reaches an assignment, it first evaluates the expression on the right side of `=`, then binds the resulting value to the name on the left. A later assignment can bind a new value to that same name. This is how a program keeps track of changing information such as a score, a counter, or a user's choice.", "Names are useful because they communicate the role of a value. `price`, `quantity`, and `total` tell a reader more than `x`, `y`, and `z`. A value can be an integer, a decimal, text, a Boolean, or a collection; the kind of value determines which operations make sense."], code: "score = 10          # assign an integer\nbonus = 5\nscore = score + bonus  # read old score, calculate, then reassign\nprint(score)", walkthrough: ["`score = 10` binds the name score to 10.", "`bonus = 5` binds another name to 5.", "Python evaluates `score + bonus` as 15, then stores that result back under score.", "The final print reads the current value of score, which is 15."] },
    sections: [
      { heading: "A name for a value", body: "A variable is a name connected to a value. The equals sign assigns the value on its right to the name on its left.", code: "score = 0\nplayer_name = \"Maya\"\nprint(score)  # 0", takeaway: "Read `score = 0` as “store 0 under the name score.”" },
      { heading: "Values can change", body: "Assigning to the same name again replaces its current value. You can also use the old value to calculate a new one.", code: "score = 0\nscore = score + 10\nprint(score)  # 10" },
      { heading: "Names have jobs", body: "Choose names that make the value's role clear. In a loop, one name might mean the current item while another remembers a total." },
      { heading: "Different kinds of values", body: "A variable can refer to different kinds of values, such as a whole number, decimal, text, or a collection. The value determines which operations make sense: numbers can be added, while text can be joined.", code: "level = 4          # integer\nprogress = 0.5     # decimal\nname = \"Maya\"    # text\nitems = [\"book\"] # list" },
      { heading: "Assignment is not the same as comparison", body: "A single `=` assigns a value. A double `==` asks whether two values are equal and produces True or False.", code: "answer = 42\nis_correct = answer == 42  # True" },
    ], checkpoint: "If `lives = 3` runs and then `lives = lives - 1`, what value does lives hold?", practicePrompt: "Write a function that adds 10 to a starting score and returns the new score.",
    workedExamples: [
      { title: "Update a score step by step", code: "score = 4\nscore = score + 3\nscore = score * 2\nprint(score)", explanation: "First score is 4. The second assignment reads the old 4, adds 3, and stores 7. The third reads 7, multiplies it by 2, and stores 14. Assignment happens after the expression on the right has been evaluated.", output: "14" },
      { title: "Track more than one value", code: "price = 12\nquantity = 3\ntotal = price * quantity\nprint(total)", explanation: "Each name has a clear role: price is the cost of one item, quantity is how many items, and total is their combined cost. Naming the intermediate values makes the calculation easier to read and change.", output: "36" },
    ],
    commonMistakes: [
      { mistake: "Using a name before assigning a value to it.", correction: "Give the variable a value before the line that reads it; otherwise Python raises NameError." },
      { mistake: "Using `=` when you meant to compare values.", correction: "Use `=` to assign and `==` to ask whether two values are equal." },
      { mistake: "Expecting `score + 1` to change score by itself.", correction: "Store the result back: `score = score + 1`, or use the shorter `score += 1`." },
    ], recap: ["A variable name refers to a value.", "The right side of an assignment is evaluated before the new value is stored.", "Use clear names to show each value's role."],
    sources: [{ label: "Python tutorial: An informal introduction", url: "https://docs.python.org/3/tutorial/introduction.html" }],
  },
  conditions: {
    title: "Conditions", subtitle: "Help your code choose what to do next.", objective: "Use a true-or-false comparison to choose which block of code runs.",
    exerciseId: "condition-choice-01",
    introduction: { heading: "How conditions guide a program", body: ["A condition is a question that Python can answer with `True` or `False`. Comparisons such as `age >= 18` and membership checks such as `name in friends` produce one of these Boolean values. An `if` statement uses that answer to decide whether a block should run.", "An `if` / `elif` / `else` chain is checked from top to bottom. Python runs the first branch whose condition is true and skips the rest of that chain. This makes order important: a broad condition placed too early can catch a value before a more specific branch gets a chance to handle it.", "Conditions can be combined. `and` means every part must be true, `or` means at least one part must be true, and `not` flips a truth value. Indentation marks which instructions belong to each branch, so consistent indentation is part of how Python understands the decision."], code: "temperature = 28\nif temperature < 10:\n    label = \"cold\"\nelif temperature <= 25:\n    label = \"mild\"\nelse:\n    label = \"warm\"", walkthrough: ["Python checks whether 28 is less than 10. It is false, so the first block is skipped.", "Next it checks whether 28 is at most 25. That is also false.", "No earlier branch matched, so the `else` block runs and label becomes warm."] },
    sections: [
      { heading: "Ask a yes-or-no question", body: "A condition compares values and produces True or False. An `if` runs its indented block only when the condition is true.", code: "temperature = 28\nif temperature > 25:\n    message = \"Warm day\"" },
      { heading: "Choose another path", body: "Use `else` for the alternative path. Use `elif` when you need to check another condition before falling back.", code: "if score >= 10:\n    badge = \"gold\"\nelif score >= 5:\n    badge = \"silver\"\nelse:\n    badge = \"starter\"" },
      { heading: "Order matters", body: "Python checks conditions from top to bottom and runs the first matching branch. Put more specific checks before broader ones.", takeaway: "Indentation shows which instructions belong to each branch." },
      { heading: "Combine questions", body: "Use `and` when both conditions must be true, `or` when either can be true, and `not` to reverse a truth value.", code: "if age >= 13 and age <= 19:\n    group = \"teen\"" },
      { heading: "Common comparisons", body: "Python comparisons include `<`, `<=`, `>`, `>=`, `==`, and `!=`. You can also check whether an item belongs to a collection with `in`.", code: "if name in friends:\n    print(\"Welcome back!\")" },
    ], checkpoint: "If `score` is 12, which badge does the example assign?", practicePrompt: "Write age_label(age) to return 'adult' for ages 18 and over, and 'minor' otherwise.",
    workedExamples: [
      { title: "Choose a shipping message", code: "weight = 4\nif weight <= 0:\n    message = \"Check the weight\"\nelif weight <= 5:\n    message = \"Standard shipping\"\nelse:\n    message = \"Heavy parcel\"\nprint(message)", explanation: "Python checks the first condition. Since 4 is not less than or equal to 0, it checks the `elif`. Four is at most 5, so it selects Standard shipping and skips the remaining branches. Exactly one branch in this chain runs.", output: "Standard shipping" },
      { title: "Combine two requirements", code: "has_ticket = True\nage = 16\nif has_ticket and age >= 13:\n    print(\"Entry allowed\")\nelse:\n    print(\"Check requirements\")", explanation: "With `and`, both the ticket check and the age check must be true. Replacing `and` with `or` would allow entry when either one is true, which is a different rule.", output: "Entry allowed" },
    ],
    commonMistakes: [
      { mistake: "Writing separate `if` statements when the choices should be exclusive.", correction: "Use `if` / `elif` / `else` when only the first matching option should run." },
      { mistake: "Putting a broad condition before a more specific one.", correction: "Order branches from the special case to the general case, because the first match wins." },
      { mistake: "Confusing `and` and `or`.", correction: "Say the rule aloud: ‘both’ usually means `and`; ‘either’ usually means `or`." },
    ], recap: ["A condition evaluates to True or False.", "Indentation defines the statements controlled by each branch.", "Python checks an if/elif chain from top to bottom."],
    sources: [{ label: "Python tutorial: if statements", url: "https://docs.python.org/3/tutorial/controlflow.html#if-statements" }],
  },
  "loop-boundaries": {
    title: "Loop Boundaries", subtitle: "Learn exactly where a Python loop starts and stops.", objective: "Predict the values a `range` loop visits and include the intended final value when needed.",
    exerciseId: "inclusive-sum-01",
    introduction: { heading: "How a range loop moves", body: ["A loop repeats a block of code for a sequence of values. Python's `for` loop asks for the next value from an iterable, assigns that value to the loop variable, runs the indented body, and then moves on. With `range`, the iterable describes a sequence of integers without needing to write each one out.", "The most important boundary rule is that range includes its start but excludes its stop. This is a useful design because the number of values in `range(start, stop)` is usually `stop - start`, and it lines up with Python's zero-based sequence indexes. It also means an inclusive task—such as visiting 1 through n—needs a stop of `n + 1`.", "A range can also include a step: `range(start, stop, step)`. A positive step moves upward; a negative step moves downward. If the step points away from the stop, the sequence is empty. To debug a boundary, list the start, the stop, the step, and the values that are actually visited."], code: "for page in range(1, 4):\n    print(page)\n# The values are 1, 2, 3; 4 is the excluded stop.", walkthrough: ["Start at 1 and visit it because the start is included.", "Increase by the default step of 1: next visit 2, then 3.", "The next value would be 4, which is the stop, so the loop finishes before visiting it."] },
    sections: [
      { heading: "The stop is excluded", body: "`range(start, stop)` includes start, then moves toward stop. It stops just before stop, so `range(1, 5)` visits 1, 2, 3, and 4.", code: "for number in range(1, 5):\n    print(number)\n# 1, 2, 3, 4" },
      { heading: "Include the last number", body: "To visit every whole number from 1 through n, use n + 1 as the exclusive stop.", code: "for number in range(1, n + 1):\n    print(number)" },
      { heading: "Check small edges", body: "Try the smallest allowed input and a one-item range. These reveal missing first or last values quickly.", takeaway: "The loop's last visited value is one less than its stop value." },
      { heading: "Add a step size", body: "`range` can take a third value called step. A step of 2 skips every other number; a negative step counts downward.", code: "list(range(2, 9, 2))  # [2, 4, 6, 8]\nlist(range(5, 0, -1)) # [5, 4, 3, 2, 1]" },
      { heading: "Often, loop over items directly", body: "Use `range` when you need a numeric sequence. When you already have a list or string, a `for` loop can visit its items directly.", code: "for fruit in [\"pear\", \"plum\"]:\n    print(fruit)" },
    ], checkpoint: "Which values does `range(2, 6)` visit?", practicePrompt: "Write a function that returns a list of numbers from 1 through n, including n.",
    workedExamples: [
      { title: "Visit every position in a list", code: "colors = [\"red\", \"blue\", \"green\"]\nfor index in range(len(colors)):\n    print(index, colors[index])", explanation: "The list has length 3, so `range(len(colors))` means `range(3)` and produces indexes 0, 1, and 2. Python lists start at index 0. In everyday code, looping over the colors directly is often simpler; use indexes when the position itself matters.", output: "0 red\n1 blue\n2 green" },
      { title: "Build an inclusive sequence", code: "def numbers_through(n):\n    result = []\n    for number in range(1, n + 1):\n        result.append(number)\n    return result\n\nprint(numbers_through(4))", explanation: "The intended values begin at 1 and end at 4. Since range excludes its stop, the stop must be 5, which is `n + 1`. Appending inside the loop saves each visited value.", output: "[1, 2, 3, 4]" },
    ],
    commonMistakes: [
      { mistake: "Using `range(1, n)` for values 1 through n.", correction: "Because the stop is excluded, use `range(1, n + 1)` when n must be included." },
      { mistake: "Assuming `range(5)` begins at 1.", correction: "A one-argument range starts at 0: `range(5)` produces 0 through 4." },
      { mistake: "Using a step that moves away from the stop.", correction: "A descending range needs a negative step, such as `range(5, 0, -1)`." },
    ], recap: ["`range(stop)` starts at 0 and excludes stop.", "`range(start, stop)` includes start and excludes stop.", "The optional third argument controls how far the value changes each turn."],
    sources: [{ label: "Python tutorial: for and range", url: "https://docs.python.org/3/tutorial/controlflow.html#for-statements" }, { label: "Python built-in range reference", url: "https://docs.python.org/3/library/stdtypes.html#range" }],
  },
  accumulators: {
    title: "Accumulators", subtitle: "Build a total one small step at a time.", objective: "Initialize a running count or total before a loop, then update it without losing earlier work.",
    exerciseId: "count-even-01",
    introduction: { heading: "How an accumulator remembers work", body: ["An accumulator is a variable that stores a result while a loop processes items. On each turn, the program takes the value already stored, combines it with information from the current item, and assigns the updated result back to the accumulator. The name might store a sum, a count, a product, or the best item seen so far.", "Its starting value matters. A sum usually starts at zero because zero does not change a sum. A product usually starts at one because multiplying by one preserves a product. A count starts at zero because no matching items have been seen yet. For a best-so-far search, initialize from a real item so the starting answer is valid.", "The update belongs inside the loop so it happens for each item. It must use the previous accumulated value: `total = total + number` or `total += number`. Writing `total = number` replaces the saved result with only the current item, losing earlier work. Trace the accumulator after every turn to catch that mistake."], code: "total = 0\nfor number in [4, 7, 2]:\n    total += number\n# total changes: 0 -> 4 -> 11 -> 13", walkthrough: ["Before the loop, total is 0.", "First turn adds 4, so total becomes 4.", "Second turn adds 7 to the saved 4, so total becomes 11.", "Third turn adds 2 to 11, giving the final total 13."] },
    sections: [
      { heading: "Start with the neutral value", body: "A sum starts at 0 because adding zero changes nothing. A count also starts at 0 because no matches have been found yet.", code: "total = 0\ncount = 0" },
      { heading: "Keep what you already collected", body: "On each loop turn, combine the old total with the new value. Assigning just the new value overwrites earlier turns.", code: "total = 0\nfor number in [2, 3, 4]:\n    total = total + number\n# total is 9" },
      { heading: "Update only when appropriate", body: "For a count, increase it only when the current item matches the condition. For a total, add the amount contributed by the current item.", takeaway: "Initialize before the loop; update inside it." },
      { heading: "A count and a sum are both accumulators", body: "A count usually increases by one for each match. A sum grows by the value contributed by each item. Their updates differ, but both preserve the previous result.", code: "count = 0\ntotal = 0\nfor price in [2, 3]:\n    count += 1\n    total += price" },
      { heading: "Accumulate a best-so-far value", body: "Not every accumulator is a number total. A `best` variable can remember the largest or smallest item found so far, updating only when a better candidate appears.", code: "largest = numbers[0]\nfor number in numbers:\n    if number > largest:\n        largest = number" },
    ], checkpoint: "After adding 2 and then 3 to a total that began at zero, what should the total be?", practicePrompt: "Write a function that counts how many numbers in a list are even.",
    workedExamples: [
      { title: "Add only values that pass a test", code: "numbers = [3, 8, 2, 7]\ntotal = 0\nfor number in numbers:\n    if number % 2 == 0:\n        total += number\nprint(total)", explanation: "The remainder operator `%` checks whether a value divides evenly by 2. The condition is true for 8 and 2, so those values are added to total. The total remains unchanged for 3 and 7.", output: "10" },
      { title: "Count matching items", code: "words = [\"sun\", \"planet\", \"moon\"]\ncount = 0\nfor word in words:\n    if len(word) > 3:\n        count += 1\nprint(count)", explanation: "A count records how many items match, so it starts at zero and increases by exactly one for each match. It does not add the word length: the question asks how many words, not how many letters.", output: "2" },
    ],
    commonMistakes: [
      { mistake: "Setting `total = number` on every turn.", correction: "That forgets earlier items. Use `total += number` to combine the old total with the current value." },
      { mistake: "Starting a sum or count at 1 without a reason.", correction: "A sum of no items and a count of no matches are both zero." },
      { mistake: "Changing the accumulator outside the loop by accident.", correction: "Place the update inside the loop so it happens once for each item." },
    ], recap: ["Initialize the stored result before the loop.", "Use a count when you need the number of matches; use a sum when you need their combined value.", "Each update should use the previous accumulated result."],
    sources: [{ label: "Python tutorial: for loops and iteration", url: "https://docs.python.org/3/tutorial/controlflow.html#for-statements" }, { label: "Python tutorial: looping techniques", url: "https://docs.python.org/3/tutorial/datastructures.html#looping-techniques" }],
  },
  "while-loops": {
    title: "While loops", subtitle: "Repeat an action while a condition remains true.", objective: "Trace a while-loop condition and update the state so the loop eventually stops.",
    exerciseId: "countdown-total-01",
    introduction: { heading: "How a while loop repeats", body: ["A `while` loop repeats as long as its condition evaluates to true. Python checks the condition before the first turn and again after every completed turn. When the condition becomes false, Python leaves the loop and continues with the first statement after its body. Because the check comes first, a loop can run zero times if its condition is false at the start.", "A while loop is useful when you do not know in advance how many repetitions are needed—for example, keep asking until input is valid, or keep moving until a target is reached. A `for` loop is often clearer when you already have a collection or a known sequence to visit.", "A safe while loop needs three things: a starting state, a condition that describes when to continue, and an update inside the body that can eventually make the condition false. If the update is missing or moves in the wrong direction, the loop may never stop. Try writing down the state at each condition check before running the code."], code: "remaining = 3\nwhile remaining > 0:\n    print(remaining)\n    remaining -= 1\nprint(\"Finished\")", walkthrough: ["The first check asks whether 3 is greater than 0. It is, so the body runs.", "The body prints 3 and decreases remaining to 2. The condition is checked again.", "The same process prints 2, then 1. After the last update, remaining is 0.", "The condition `0 > 0` is false, so the loop ends and Finished is printed."] },
    sections: [
      { heading: "Check before each turn", body: "A `while` loop checks its condition before running the body. If the condition is false at the start, the body runs zero times.", code: "current = 3\nwhile current > 0:\n    print(current)\n    current -= 1" },
      { heading: "Make progress", body: "Update a value used by the condition on every turn. If it never moves toward making the condition false, the loop can continue forever.", code: "current -= 1  # moves toward zero" },
      { heading: "Trace a few turns", body: "Write down the value before and after each turn. Confirm that the condition eventually becomes false.", takeaway: "A changing state and a reachable stopping condition make a loop finish." },
      { heading: "The condition is checked again", body: "After the body runs, Python returns to the condition. When it becomes false, the loop ends and execution continues after the loop.", code: "remaining = 3\nwhile remaining > 0:\n    print(remaining)\n    remaining -= 1\nprint(\"Done!\")" },
      { heading: "Choose for or while", body: "Use `for` when going through items or a known sequence. Use `while` when repetition depends on a condition that may change as the program runs.", takeaway: "Before running a while-loop, identify the condition and the update that will eventually make it false." },
    ], checkpoint: "Starting at 2, how many times does `while current > 0` run if current decreases by 1 each turn?", practicePrompt: "Write a function that counts how many decrements it takes for a nonnegative number to reach zero.",
    workedExamples: [
      { title: "Repeat until a target is reached", code: "steps = 0\nposition = 0\nwhile position < 10:\n    position += 3\n    steps += 1\nprint(position, steps)", explanation: "The loop checks whether position is below 10 before each turn. It takes the values 0, 3, 6, and 9 at the checks; after the fourth update position is 12. The next check is false, so it stops. A while-loop can pass a threshold if its update jumps by more than one.", output: "12 4" },
      { title: "Ask again until input is valid", code: "answer = \"\"\nwhile answer != \"yes\":\n    answer = input(\"Type yes to continue: \")\nprint(\"Continuing\")", explanation: "This is a common condition-controlled pattern: ask repeatedly while the answer is not valid. The value used in the condition changes inside the loop. In this example, the learner's input eventually makes the condition false.", output: "The prompt repeats until the user types yes." },
    ],
    commonMistakes: [
      { mistake: "Forgetting to update a variable used in the condition.", correction: "Check that every loop turn changes the state toward the stopping point." },
      { mistake: "Updating in the wrong direction.", correction: "For `while number > 0`, subtracting can reach the stop; adding makes the condition stay true longer." },
      { mistake: "Assuming the body runs at least once.", correction: "The condition is checked first, so a false condition means zero turns." },
    ], recap: ["A while-loop repeats only while its condition is true.", "The condition is checked before every turn.", "Make sure the loop can reach a false condition."],
    sources: [{ label: "Python tutorial: while statements", url: "https://docs.python.org/3/reference/compound_stmts.html#the-while-statement" }, { label: "Python tutorial: break and continue", url: "https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements" }],
  },
  "loop-mastery": {
    title: "Loop mastery challenge", subtitle: "Mix your loop skills in a fresh problem.", objective: "Choose clear variable roles and combine iteration, conditions, and state updates to solve a new task.",
    exerciseId: "longest-word-01",
    introduction: { heading: "How to plan a loop problem", body: ["A loop problem is easier when you decide what one turn should do before writing code. Identify the collection or range being visited, what information the current item provides, and what the function must remember between turns. Give each of those jobs a clear variable name.", "Many problems follow a repeatable plan: initialize remembered state, visit each item, use a condition to decide whether it matters, update the state, then return the final result. For example, finding the longest word requires a current candidate and a separate best-so-far word. Counting matches requires a count. Summing values requires a total. Choosing the right state is the heart of the algorithm.", "Then test the boundaries and rules: Is the input empty? Is there just one item? What should happen on a tie? Should the first or last matching item win? Write tests for those cases and trace the variables turn by turn. This makes hidden assumptions visible and helps you distinguish a boundary issue from a variable-role or update issue."], code: "best = words[0]               # remembered answer\nfor candidate in words[1:]:   # current item\n    if len(candidate) > len(best):\n        best = candidate\nreturn best", walkthrough: ["Initialize best with a real answer from the input.", "Visit each remaining candidate one at a time.", "Compare the candidate's length with the best answer's length.", "Replace best only when the candidate is strictly longer; otherwise retain the earlier answer."] },
    sections: [
      { heading: "Give each variable one job", body: "A loop variable can hold the current item. Other variables can hold a count, a running total, or the best answer seen so far.", code: "best = words[0]\nfor word in words:\n    if len(word) > len(best):\n        best = word" },
      { heading: "Compare, then remember", body: "When the current candidate is better than the saved answer, update the best-so-far variable. Otherwise, keep the earlier answer.", code: "if len(word) > len(best):\n    best = word" },
      { heading: "Test more than the happy path", body: "Try one item, a tie, and a case where the first item is already the answer. Define how ties should behave.", takeaway: "Before changing a variable, ask what information it is meant to remember." },
      { heading: "Get an index and item together", body: "When you need both a position and its value, `enumerate` provides them on each turn. This can make index-based loops clearer.", code: "for index, word in enumerate([\"cat\", \"owl\"]):\n    print(index, word)" },
      { heading: "Search with a clear stopping rule", body: "A search loop can stop early when it finds what it needs. `break` exits the loop; `continue` skips to its next turn. Use them when they make the control flow easier to follow.", code: "for word in words:\n    if word == target:\n        found = True\n        break" },
    ], checkpoint: "In the example, which variable is the current candidate, and which remembers the best answer?", practicePrompt: "Write a function that returns the first longest word in a nonempty list.",
    workedExamples: [
      { title: "Keep the first longest word", code: "def longest_word(words):\n    best = words[0]\n    for word in words[1:]:\n        if len(word) > len(best):\n            best = word\n    return best\n\nprint(longest_word([\"ant\", \"tiger\", \"horse\"]))", explanation: "The first word is a valid starting answer, so best begins as words[0]. Each later word is the current candidate. If it is strictly longer, replace best. Using `>` rather than `>=` keeps the first word when there is a tie.", output: "tiger" },
      { title: "Build a frequency dictionary", code: "counts = {}\nfor color in [\"blue\", \"red\", \"blue\"]:\n    if color not in counts:\n        counts[color] = 0\n    counts[color] += 1\nprint(counts)", explanation: "This combines roles: color is the current item, counts stores the running number for each color, and `counts[color]` is updated for just that item. The membership check makes sure a new key starts at zero before it is incremented.", output: "{'blue': 2, 'red': 1}" },
    ],
    commonMistakes: [
      { mistake: "Using the current item where the saved best answer is needed.", correction: "Give current and best-so-far separate names, then compare their relevant properties." },
      { mistake: "Initializing best to an arbitrary number or empty string.", correction: "When the input is nonempty, initializing from its first item avoids assumptions about valid values." },
      { mistake: "Ignoring what a tie should do.", correction: "Choose `>` to keep the first best item or `>=` to replace it with a later tie, based on the task rule." },
    ], recap: ["State each variable's job before writing the loop.", "Initialize best-so-far from a valid candidate.", "Test single-item inputs, ties, and cases where the first item wins."],
    sources: [{ label: "Python tutorial: looping techniques and enumerate", url: "https://docs.python.org/3/tutorial/datastructures.html#looping-techniques" }, { label: "Python tutorial: break and continue", url: "https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements" }],
  },
};
