import { topicLessons } from "@/lib/topic-lessons";
import type { IslandActor, MapPosition } from "@/types/game";

const variables = topicLessons.variables;

export const firstIsland = {
  name: "The First Island",
  chapter: "Python Foundations",
  objective: "Follow the island trail and learn how Python remembers values.",
  startingCoins: 0,
  interactionRadius: 9,
  playerStart: { x: 41, y: 88 } satisfies MapPosition,
  challenge: {
    actorId: "island-scout",
    exerciseId: variables.exerciseId ?? "starting-value-01",
    title: "The Scout's Variable Trial",
    reward: 50,
  },
};

export const firstIslandActors: IslandActor[] = [
  {
    id: "beach-cartographer",
    name: "Beach Cartographer",
    sprite: "traveler",
    frames: 4,
    role: "teacher",
    reaction: "Every program begins by giving important information a name.",
    position: { x: 38, y: 84 },
    scale: 0.52,
    lesson: {
      id: "variable-names",
      order: 1,
      title: variables.sections[0].heading,
      eyebrow: "Lesson 1 · Meet variables",
      body: [variables.introduction.body[0], variables.sections[0].body],
      code: variables.sections[0].code,
      takeaway: variables.sections[0].takeaway,
    },
  },
  {
    id: "shore-emberbug",
    name: "Emberbug",
    sprite: "emberbug",
    frames: 8,
    role: "teacher",
    reaction: "Values come in different forms. Some count, some describe, and some collect.",
    position: { x: 68, y: 84 },
    scale: 0.38,
    lesson: {
      id: "value-types",
      order: 2,
      title: variables.sections[3].heading,
      eyebrow: "Lesson 2 · Know your values",
      body: [variables.sections[3].body],
      code: variables.sections[3].code,
    },
  },
  {
    id: "forest-bristleback",
    name: "Bristleback",
    sprite: "bristleback",
    frames: 4,
    role: "teacher",
    reaction: "A stored value can change as the journey changes.",
    position: { x: 45, y: 57 },
    scale: 0.58,
    lesson: {
      id: "changing-values",
      order: 3,
      title: variables.sections[1].heading,
      eyebrow: "Lesson 3 · Update what you know",
      body: [variables.sections[1].body, variables.workedExamples[0].explanation],
      code: variables.workedExamples[0].code,
      takeaway: `The example finishes with ${variables.workedExamples[0].output}.`,
    },
  },
  {
    id: "trail-fox",
    name: "Trail Fox",
    sprite: "fox",
    frames: 6,
    role: "teacher",
    reaction: "Good names make a trail easy to follow.",
    position: { x: 40, y: 29 },
    scale: 0.68,
    lesson: {
      id: "clear-names",
      order: 4,
      title: variables.sections[2].heading,
      eyebrow: "Lesson 4 · Leave a clear trail",
      body: [variables.sections[2].body, variables.introduction.body[2]],
      takeaway: "Prefer names such as score, quantity, and total over x, y, and z.",
    },
  },
  {
    id: "cave-keeper",
    name: "Cave Keeper",
    sprite: "caveKeeper",
    frames: 4,
    role: "teacher",
    reaction: "Most broken spells are familiar mistakes in disguise.",
    position: { x: 13.5, y: 39 },
    scale: 0.5,
    lesson: {
      id: "variable-mistakes",
      order: 5,
      title: "Avoid the common traps",
      eyebrow: "Lesson 5 · Debug the cave",
      body: variables.commonMistakes.map((item) => `${item.mistake} ${item.correction}`),
      takeaway: variables.recap[1],
    },
  },
  {
    id: "mossling",
    name: "Mossling",
    sprite: "mossling",
    frames: 4,
    role: "teacher",
    reaction: "One symbol stores a value. Two symbols ask a question.",
    position: { x: 85, y: 30 },
    scale: 0.8,
    lesson: {
      id: "assignment-comparison",
      order: 6,
      title: variables.sections[4].heading,
      eyebrow: "Lesson 6 · Read the symbols",
      body: [variables.sections[4].body],
      code: variables.sections[4].code,
      takeaway: "Use = to assign and == to compare.",
    },
  },
  {
    id: "island-scout",
    name: "Island Scout",
    sprite: "scout",
    frames: 4,
    role: "challenge",
    reaction: "Complete every lesson, then show me what you can build.",
    position: { x: 78, y: 34 },
    scale: 0.62,
  },
  {
    id: "cave-slime",
    name: "Dewdrop",
    sprite: "slime",
    frames: 5,
    role: "ambient",
    reaction: "Dewdrop jiggles encouragingly.",
    position: { x: 14, y: 30 },
    scale: 0.7,
  },
  {
    id: "cliff-slime",
    name: "Pebble",
    sprite: "slime",
    frames: 5,
    role: "ambient",
    reaction: "Pebble has found a particularly comfortable rock.",
    position: { x: 20, y: 22 },
    scale: 0.75,
  },
];

export const orderedFirstIslandLessons = firstIslandActors
  .filter((actor) => actor.lesson)
  .sort((left, right) => (left.lesson?.order ?? 0) - (right.lesson?.order ?? 0));
